name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build password generator
      run: gcc -o passgen passgen.c -Wall -Wextra
    
    - name: Run comprehensive tests
      run: ./test.sh
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: passgen-binary
        path: passgen